name: Deploy to VPS

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci

      - name: Build frontend
        run: |
          npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 109.70.24.185
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Обновляем систему
            apt update && apt upgrade -y

            # Устанавливаем Node.js если не установлен
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
              apt-get install -y nodejs
            fi

            # Устанавливаем nginx если не установлен
            if ! command -v nginx &> /dev/null; then
              apt install nginx -y
              systemctl start nginx
              systemctl enable nginx
            fi

            # Создаем директорию для проекта
            cd /root/www/nakhodka-vodokanal.ru/vodokanal-front

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 109.70.24.185
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "."
          target: "/root/www/nakhodka-vodokanal.ru/vodokanal-front"
          strip_components: 0

      - name: Setup and start application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 109.70.24.185
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /root/www/nakhodka-vodokanal.ru/vodokanal-front

            # Устанавливаем зависимости
            npm ci --production

            # Создаем .env файл если его нет

            # Останавливаем старый процесс если есть
            pm2 stop vodokanal-front || true
            pm2 delete vodokanal-front || true

            # Устанавливаем PM2 если не установлен
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Запускаем приложение через PM2
            pm2 start ecosystem.config.js --only next-dev
            pm2 save
            pm2 startup 


            nginx -t && systemctl reload nginx

            echo "Deployment completed successfully!"
            echo "PM2 Status:"
            pm2 status
